name: premflix
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.4
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.7.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
